//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTasks
    {
        public int TreatmentId { get; set; }
        public int StepId { get; set; }
        public int VisitTaskId { get; set; }
        public int VisitId { get; set; }
        public int TreatmenPosition { get; set; }
        public Nullable<int> StepOptionId { get; set; }
        public string Description { get; set; }
    
        public virtual StepOptions StepOptions { get; set; }
        public virtual TreatmentSteps TreatmentSteps { get; set; }
        public virtual Visits Visits { get; set; }
    }
}
