
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Salon.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Settings
{

    public int SettingID { get; set; }

    public short AnonymizeUserByDays { get; set; }

    public short AnonymizeCustomerByDays { get; set; }

    public short DeleteUserByDays { get; set; }

    public short DeleteCustomerByDays { get; set; }

}

}
