//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
public partial class Connections
{

    public int ConnectionId { get; set; }

    public int ConnectionTypeId { get; set; }

    public int CustomerId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    

    public virtual ConnectionTypes ConnectionTypes { get; set; }

    public virtual Customers Customers { get; set; }

}
}
