//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    
    public partial class GetWorkPerClass
    {
        public string StudentName { get; set; }
        public string TeacherName { get; set; }
        public string Class { get; set; }
        public string Treatement { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int TreatmentId { get; set; }
    }
}
