//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    
    public partial class GetWorkPerClass
    {
        public int TreatmentId { get; set; }
        public string StudentName { get; set; }
        public string TeacherName { get; set; }
        public string Class { get; set; }
        public string Treatement { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Room { get; set; }
    }
}
