
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Salon.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Settings
{

    public int SettingID { get; set; }

    public short AnonymizeUserByDays { get; set; }

    public short AnonymizeCustomerByDays { get; set; }

    public short DeleteUserByDays { get; set; }

    public short DeleteCustomerByDays { get; set; }

}

}
