//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitTasks
    {
        public int TreatmentId { get; set; }
        public int StepId { get; set; }
        public int VisitTaskId { get; set; }
        public int VisitId { get; set; }
        public int TreatmenPosition { get; set; }
        public Nullable<int> StepOptionId { get; set; }
        public string Description { get; set; }
    
        public virtual StepOptions StepOptions { get; set; }
        public virtual TreatmentSteps TreatmentSteps { get; set; }
        public virtual Visits Visits { get; set; }
    }
}
